### PR TITLE
Add IN clause param interpolation

### PR DESCRIPTION
**Pull request by dvivchar**
Adds `IN` clause param interpolation.

```scala
val collection = List(1, 2, 3)
sql"select name, age from users where id in ($collection)"
```

equals to `Sql(select name, age from users where id in (?,?,?), 1, 2, 3)`

/claim #104

### CODE REVIEW

**Comment by dvivchar** [comment]
@jdegoes is there any other way to receive bounties? Unfortunately Algora do not work for Ukrainians.

**Comment by jdegoes** [comment]
That's a big problem, I will chat with their team!

**Comment by zcesur** [comment]
hey @dvivchar this is Zaf, one of the founders at Algora. Our sincere apologies for the inconvenience here. I understand the  bounty bot comment note "📝 Before proceeding, please make sure you can [receive payouts](https://docs.algora.io/bounties/payments#country-support) in your country" is easy to miss, will fix that.

however, **we do have alternative payment methods** in place and we'll make sure you receive your reward promptly. since you didn't register on Algora and we don't know your email, could you kindly email us at zafer@algora.io and we'll get this sorted asap. thank you for your contribution and collaboration!

**Comment by dvivchar** [comment]
hey @zcesur thank you for a quick response, I'm having mail conversation with ioannis@algora.io.

File: core/src/main/scala/zio/jdbc/Sql.scala [hunk 1]
```diff
@@ -210,6 +221,15 @@ object Sql {
     implicit val sqlDateSetter: Setter[java.sql.Date] = forSqlType((ps, i, value) => ps.setDate(i, value), Types.DATE)
     implicit val sqlTimeSetter: Setter[java.sql.Time] = forSqlType((ps, i, value) => ps.setTime(i, value), Types.TIME)
 
+    implicit def sqlIterableSetter[A](implicit setter: Setter[A]): Setter[Seq[A]] =
```
Comment (jdegoes) [inline core/src/main/scala/zio/jdbc/Sql.scala:224]: I think due to contravariant type classes being broken in Scala 2.x, the invariance means that we need to have concrete classes:

```scala
Setter[Chunk[A]]
Setter[List[A]]
Setter[Vector[A]]
Setter[Set[A]]
Setter[Array[A]]
```

Probably those types are enough.

**Review by jdegoes — CHANGES_REQUESTED** [review]
Looks good, just one small tweak and then good to merge!

**Comment by dvivchar** [comment]
@jdegoes refactored to concrete collection types, ready to be reviewed again

**Comment by jdegoes** [comment]
@dvivchar Can you fix merge conflicts, then I will merge? Thanks for your work on this!

**Comment by dvivchar** [comment]
> @dvivchar Can you fix merge conflicts, then I will merge? Thanks for your work on this!

resolved!

**Comment by jdegoes** [comment]
@dvivchar Sorry, another commit made it in, looks like one more conflict. Hopefully last one!

**Comment by dvivchar** [comment]
@jdegoes resolved!

**Comment by dvivchar** [comment]
unfortunately it's failing with 
```
[error] ## Exception when compiling 2 sources to /home/runner/work/zio-jdbc/zio-jdbc/core/target/scala-2.12/test-classes
[error] java.lang.NullPointerException
[error] scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateMatch(MatchTranslation.scala:214)
[error] scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateMatch$(MatchTranslation.scala:194)
```
I guess it's not related to changes in this PR...

**Comment by adamgfraser** [comment]
@dvivchar All tests are passing on `main` so it does appear to be related to this PR. That looks like a crash in the Scala compiler which unfortunately means there is a compilation error but you are not getting a helpful error message. I would try compiling that version and retrace my steps to the last time it did compile on Scala 2.12 to diagnose.

**Comment by dvivchar** [comment]
@adamgfraser you are right,
issue was with `Chunk.from(seq)`. Not sure why but compiler crashes on it, while `Chunk.apply` works ok.

**Comment by adamgfraser** [comment]
@dvivchar `from` was added in the Scala 2.13 collections redesign so doesn't exist in Scala 2.12.

**Review by adamgfraser — APPROVED** [review]

**Comment by dvivchar** [comment]
@jdegoes could you please approve?
